apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  labels:
    tier: backend
data:
  config: {
    server {
      index index.php index.html;
      error_log /var/log/nginx/error/log;
      access_log /var/log/nginx/access.log;

      root /code/app/public;

      location / {
        try_files $url $url/ /index.php?$query_string;
      }

      location ~ .php$ {
        try_files $url =404;
        fastcgi_split_path_info ^(.+.php)(/.+)$;
        fastcgi_pass localhost:9000;
        fastcgi_index index.php;
        include fastcgi params;
        fastcgi_param SCRIPT_FILENNAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
      }
    }
  }